#!/usr/bin/env python3
"""
Fetch velocity band batting stats for WBC catcher game hard mode.
Uses pybaseball Statcast data (2024-2025 seasons).

Output: ../src/data/velocityBandData.ts

Usage:
    pip install pybaseball pandas
    python fetch_velocity_bands.py
"""
import json
from pybaseball import statcast_batter

BANDS = [
    "60-62", "63-65", "66-68", "69-71", "72-74", "75-77",
    "78-80", "81-83", "84-86", "87-89", "90-92", "93-95",
    "96-98", "99-101", "102-105"
]

BAND_RANGES = [
    (60, 62), (63, 65), (66, 68), (69, 71), (72, 74), (75, 77),
    (78, 80), (81, 83), (84, 86), (87, 89), (90, 92), (93, 95),
    (96, 98), (99, 101), (102, 105)
]

# Batter ID mapping (MLB MLBAM IDs)
BATTERS = {
    # Japan
    "ohtani": 660271,
    "suzuki": 673548,
    "yoshida": 807799,
    "murakami": 808959,
    # DOM
    "soto": 665742,
    "tatis": 665487,
    "guerrero": 665489,
    "machado": 592518,
    "caminero": 694557,  # approximate
    "jrod": 677594,
    "marte": 516782,
    "pena": 665161,
    "wells": 669224,
    "perdomo": 672695,
    "cruz": 665833,
    "ramirez": 608070,
}

HIT_EVENTS = {'single', 'double', 'triple', 'home_run'}
AB_EVENTS = {'single', 'double', 'triple', 'home_run',
             'strikeout', 'field_out', 'grounded_into_double_play',
             'force_out', 'fielders_choice', 'fielders_choice_out',
             'double_play', 'triple_play', 'field_error',
             'strikeout_double_play'}
TOTAL_BASES = {'single': 1, 'double': 2, 'triple': 3, 'home_run': 4}


def get_band(speed):
    for i, (lo, hi) in enumerate(BAND_RANGES):
        if lo <= speed <= hi:
            return BANDS[i]
    return None


def compute_batter_bands(mlbam_id, start='2024-01-01', end='2025-12-31'):
    """Fetch Statcast data and compute BA/SLG per velocity band."""
    df = statcast_batter(start, end, mlbam_id)
    if df is None or df.empty:
        return None, 0, 0

    # Filter to pitches with release_speed and events
    df = df.dropna(subset=['release_speed'])
    events_df = df.dropna(subset=['events'])

    # Overall averages
    ab_mask = events_df['events'].isin(AB_EVENTS)
    total_ab = ab_mask.sum()
    total_hits = events_df['events'].isin(HIT_EVENTS).sum()
    total_tb = events_df[events_df['events'].isin(HIT_EVENTS)]['events'].map(
        lambda e: TOTAL_BASES.get(e, 0)).sum()

    avg_ba = total_hits / total_ab if total_ab > 0 else 0.250
    avg_slg = total_tb / total_ab if total_ab > 0 else 0.400

    # Per-band stats
    bands = {}
    for band_label, (lo, hi) in zip(BANDS, BAND_RANGES):
        band_events = events_df[
            (events_df['release_speed'] >= lo) &
            (events_df['release_speed'] <= hi)
        ]
        ab = band_events['events'].isin(AB_EVENTS).sum()
        if ab < 5:  # Skip bands with insufficient data
            bands[band_label] = {"ba": round(avg_ba, 3), "slg": round(avg_slg, 3)}
            continue

        hits = band_events['events'].isin(HIT_EVENTS).sum()
        tb = band_events[band_events['events'].isin(HIT_EVENTS)]['events'].map(
            lambda e: TOTAL_BASES.get(e, 0)).sum()

        ba = hits / ab
        slg = tb / ab
        bands[band_label] = {"ba": round(ba, 3), "slg": round(slg, 3)}

    return bands, round(avg_ba, 3), round(avg_slg, 3)


def main():
    results = {}
    for name, mlbam_id in BATTERS.items():
        print(f"Fetching {name} (ID: {mlbam_id})...")
        try:
            bands, avg_ba, avg_slg = compute_batter_bands(mlbam_id)
            if bands:
                results[name] = {
                    "avgBA": avg_ba,
                    "avgSLG": avg_slg,
                    "bands": bands
                }
                print(f"  OK: BA={avg_ba}, SLG={avg_slg}, {len(bands)} bands")
            else:
                print(f"  SKIP: no data")
        except Exception as e:
            print(f"  ERROR: {e}")

    # Generate TypeScript file
    ts_lines = [
        "// Velocity band batting stats (3mph bands)",
        "// Source: pybaseball Statcast 2024-2025 seasons",
        f"// Generated by scripts/fetch_velocity_bands.py",
        "",
        "import type { VelocityBandStats } from './types';",
        "",
        "export interface BatterVelocityProfile {",
        "  avgBA: number;",
        "  avgSLG: number;",
        "  bands: Record<string, VelocityBandStats>;",
        "}",
        "",
    ]

    for name, data in results.items():
        ts_lines.append(f"const {name}: BatterVelocityProfile = {{")
        ts_lines.append(f"  avgBA: {data['avgBA']}, avgSLG: {data['avgSLG']},")
        ts_lines.append("  bands: {")
        for band_label, stats in data['bands'].items():
            ts_lines.append(f"    '{band_label}': {{ ba: {stats['ba']}, slg: {stats['slg']} }},")
        ts_lines.append("  },")
        ts_lines.append("};")
        ts_lines.append("")

    ts_lines.append("export const VELOCITY_BAND_DATA: Record<string, BatterVelocityProfile> = {")
    for name in results:
        ts_lines.append(f"  {name},")
    ts_lines.append("};")
    ts_lines.append("")

    output_path = "../src/data/velocityBandData.ts"
    with open(output_path, 'w') as f:
        f.write('\n'.join(ts_lines))

    print(f"\nGenerated {output_path} with {len(results)} batters")


if __name__ == '__main__':
    main()
